hardware:
  plugin: "hardware_controller/HardwareController"
  hardware_parameters:
    port: "/dev/ttyUSB0"
    baudrate: "115200"
    num_wheels: "2"

joints:
  - name: left_wheel_joint
  - name: right_wheel_joint